services:
  devbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devbox

    volumes:
      # Your repos
      - ~/dev:/workspaces

      # Git identity
      - ~/.gitconfig:/home/ubuntu/.gitconfig:ro

      # SSH keys
      - ~/.ssh/id_ed25519.pub:/home/ubuntu/.ssh/authorized_keys

      # Persist shell history only — everything else is baked into the image
      - devbox-history:/home/ubuntu/.bash_history

      # VS code extensions are installed in the container. Persist them.
      - vscode-server:/home/ubuntu/.vscode-server

    ports:
      - 2222:22
      # Node / Angular / Vite
      - "3000-3010:3000-3010"
      # .NET Kestrel
      - "5000-5010:5000-5010"
      # Go / misc
      - "8000-8010:8000-8010"
      # Flutter web
      - "8080:8080"

    stdin_open: true
    tty: true
    restart: unless-stopped

    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_NOLOGO=1

volumes:
  devbox-history:
  vscode-server: